dependencies {
    // We depend on fabric loader here to use the fabric @Environment annotations and get the mixin dependencies
    // Do NOT use other classes from fabric loader
    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    // Remove the next line if you don't want to depend on the API
    modApi "dev.architectury:architectury:${rootProject.architectury_version}"
}

architectury {
    common("fabric", "forge")
}

repositories {
    flatDir {
        dirs findProject(':common').getProjectDir().toPath().resolve("../../ArtanCoreMod/fabric/build/libs")
        dirs findProject(':common').getProjectDir().toPath().resolve("../../ArtanCoreMod/forge/build/libs")
    }
}

dependencies {
    if(Boolean.parseBoolean(is_local_artan_core)) {
        modImplementation files(file(findProject(':common').getProjectDir().toPath().resolve("../../ArtanCoreMod/fabric/build/libs")
                .resolve("Artan'sProjectCoreMOD-fabric-mc${minecraft_version}-${artan_core_local_version}-dev-shadow.jar")))
    } else {
        modImplementation "curse.maven:artancore-585454:" + artan_core_fabric_version
    }

    // JEI
    modCompileOnlyApi "mezz.jei:jei-${minecraft_version}-common-api:${jei_version}"
}

publishing {
    publications {
        mavenCommon(MavenPublication) {
            artifactId = mod_id + "-" + project.name
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
    }
}
